### ISSUE TITLE
Use Github action to build using repo2docker and push to dockerhub

### ISSUE THREAD

**Issue by psychemedia** [innovationOUtside/tm351vm-binder#10]
Someone posted a recipe on this last month — https://github.com/machine-learning-apps/repo2docker-action — so it must be pretty mature by now?!

How hard can it possibly be....?

**Comment by mmh352** [comment]
Because I use a Dockerfile for repo2docker, I can also just build using the standard docker action: https://github.com/mmh352/metadata-tutorial-container/blob/default/.github/workflows/deploy-docker.yml

In general using actions to build stuff is really quite easy, so worth giving it a shot.

**Comment by psychemedia** [comment]
@mmh352 I've been using actions [for months now](https://github.com/innovationOUtside/tm351vm-binder/tree/master/.github/workflows) to build various things and push them to Dockerhub...;-) Generally from releases.
